### ISSUE TITLE
compiling??

### ISSUE THREAD

**Issue by dzastsed** [tge-was-taken/Ortus#1]
tried to compile but it complains about .net sdk missing: 
![image](https://github.com/tge-was-taken/Ortus/assets/63074962/1227ad06-f56a-43bd-b20b-c7a7462958e9)
it however *is* installed 
![image](https://github.com/tge-was-taken/Ortus/assets/63074962/0d49c729-79f8-4ea1-8c72-e6caf0dc08bb)
or does it need earlier visual studio for compiling? tried only with 2022...

**Comment by tge-was-taken** [comment]
Thanks for the report. It's fixed now.
